### PR TITLE
Editing my bot

### PR DESCRIPTION
**Pull request by Zenrac**
Fixing redundant informations

### CODE REVIEW

**Comment by lepon01** [comment]
That's not how Markdown works
https://deploy-preview-75--discordbots.netlify.com/bots/220644154177355777/

stan loona, stan talent

**Comment by Zenrac** [comment]
Why it is working on github

**Comment by lepon01** [comment]
This is using Kramdown, the built in Markdown processor for Jekyll, the static site generator which runs this site.

You probably wanted:

```
## wow this is centered
{: .center}
```

**Comment by lepon01** [comment]
:ok_hand:

**Comment by Zenrac** [comment]
Thanks

**Pull request merged**
