### PR TITLE
Add Github OAuth to allow adding stars

### PR DESCRIPTION
**Pull request by lepon01**
This will allow users to add stars, as well as view the number of stars per project.  
This is not practical without OAuth because of GitHub's stringent ratelimits for unauthenticated requests.

A server is only required for authentication ONCE. After authentication, the server is not required.
The server has already been set up at https://auth.discordbots.co.uk/

@perryprog do not pull unless you have tested.

Thanks.

### CODE REVIEW

**Comment by lepon01** [comment]
Can't add multiple callback URLs - No local testing for authentication unless you really need to

**Comment by itslukej** [comment]
How does this appeal to people who visit the site (gamers)

**Comment by lepon01** [comment]
The GitHub integration does not appeal to gamers.

**Comment by lepon01** [comment]
image

**Pull request merged**
