### PR TITLE
Adding LxiBot

### PR DESCRIPTION
**Pull request by pacucci**
---
This pull request was created using the https://discordbots.co.uk/edit menu.

### CODE REVIEW

**Comment by lepon01** [comment]
I have doubts this is the "best bot you have ever seen", but ok, I guess.

**Comment by pacucci** [comment]
thx so much

**Comment by pacucci** [comment]
You can find a documentation on https://lxibot.gitbook.io/commands

**Comment by lepon01** [comment]
no problem

**Pull request merged**
