### PR TITLE
Adding Test

### PR DESCRIPTION
**Pull request by Andre601**
This pull request was made by the Gatsby Branch Editor.

### CODE REVIEW

**Comment by lepon01** [comment]
Quality

**Comment by Andre601** [comment]
I just made a test, to check, if that editor works, since the other person mentioned issues.

**Comment by Devoxin** [comment]
Why are you testing?

**Comment by Andre601** [comment]
In #167 was mentioned, that the editor was used, yet the file was `null.md` so I tested it now.
Editor works as it should.

**Comment by lepon01** [comment]
heh 169

**Pull request closed without merging**
